"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = [
    'bj.ico'
]
OPTIONS = {
    'iconfile': 'bj.ico',
    'packages': ["sub"],
    "includes": [
        "os",
        "platform",
        "subprocess",
        # "gevent",
        # "geventwebsocket",
        # "gevent.ssl",
        # "gevent.builtins",
        "engineio.async_drivers.threading"
    ]
}

setup(
    name="微信公众号",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
